name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: go mod 
      run: cd 2-2/ && go mod tidy

    - name: Build
      run: cd 2-2/ && go build  

    - name: commit
      run: |
        git config --global user.email zflmiy@qq.com
        git config --global user.name FLM210
        git add .
        git commit -m "update" -a

    - name: Push changes
      uses: ad-m/github-push-action@master

