name: Go

on:
  push:
    branches:    
      - "module2"
      # Push events to branches matching refs/heads/mona/octocat

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: go mod 
      run: go mod tidy

    - name: Build 
      run:  go build  
    

    - name: build Docker Image
      run: |
        docker login --username=${{ secrets.DOCKERUSERNAME }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.DOCKERPASSWORD }} 
        docker build -t registry.cn-hangzhou.aliyuncs.com/my_docker_images/httpserver:v1 . 
        docker push registry.cn-hangzhou.aliyuncs.com/my_docker_images/httpserver:v1


