name: Go

on:
  push:
    branches:    
      - main
      # Push events to branches matching refs/heads/mona/octocat
      - 'cncmapTask/2-2/'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: go mod 
      run: cd 2-2/ && go mod tidy

    - name: Build 
      run: cd 2-2/ && go build  
    
    - name: get docker hub info
      run: echo ${{ secrets.DOCKERUSERNAME }} ${{ secrets.DOCKERPASSWORD }} || echo ${secrets.DOCKERUSERNAME} ${secrets.DOCKERPASSWORD}

    # - name: build Docker Image
    #   run: |
    #     docker login --username=${{ secrets.DOCKERUSERNAME }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.DOCKERPASSWORD }} 
    #     cd 2-2/ && docker build -t httpServer:latest . #执行构建
    #     docker tag httpServer registry.cn-hangzhou.aliyuncs.com/my_docker_images/httpServer
    #     docker push registry.cn-hangzhou.aliyuncs.com/my_docker_images/httpServer 


